Post http://localhost:8080/events
Content-Type: application/json

{
    "name": "updated event",
    "description": "updated test event",
    "location": "A test location",
    "datetime": "2025-05-18T20:43:33.000Z"
}

{
    "email": "test@example.com",
    "password": "test"
}
